name: Daily deploy hook call
on:
  schedule:
    - cron: "0 1 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our deploy hook in Vercel
        run: |
          curl --request POST \
          --url '${{ secrets.DEPLOY_URL }}' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
